// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8EFPZUF9q_pRLumPchhzAkSlT8bU3zmE',
    appId: '1:298799858325:web:31b286ea2fa9e8c192d19c',
    messagingSenderId: '298799858325',
    projectId: 'saturn-40eac',
    authDomain: 'saturn-40eac.firebaseapp.com',
    storageBucket: 'saturn-40eac.firebasestorage.app',
    measurementId: 'G-0Q8SK1SNZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnm3rkpGMfiJRMf6DRqSxMZcdaoYc7-RY',
    appId: '1:298799858325:android:7357d16852f0b8c592d19c',
    messagingSenderId: '298799858325',
    projectId: 'saturn-40eac',
    storageBucket: 'saturn-40eac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX8pXMT3xO1TTI0u4oYyfdmq9ldEWznOM',
    appId: '1:298799858325:ios:806de05752bf12b292d19c',
    messagingSenderId: '298799858325',
    projectId: 'saturn-40eac',
    storageBucket: 'saturn-40eac.firebasestorage.app',
    iosBundleId: 'com.example.saturn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX8pXMT3xO1TTI0u4oYyfdmq9ldEWznOM',
    appId: '1:298799858325:ios:806de05752bf12b292d19c',
    messagingSenderId: '298799858325',
    projectId: 'saturn-40eac',
    storageBucket: 'saturn-40eac.firebasestorage.app',
    iosBundleId: 'com.example.saturn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8EFPZUF9q_pRLumPchhzAkSlT8bU3zmE',
    appId: '1:298799858325:web:71356fcb465b4eb592d19c',
    messagingSenderId: '298799858325',
    projectId: 'saturn-40eac',
    authDomain: 'saturn-40eac.firebaseapp.com',
    storageBucket: 'saturn-40eac.firebasestorage.app',
    measurementId: 'G-WQ08KJGV3V',
  );
}
